### ISSUE TITLE
error when dumping some apps

### ISSUE THREAD

**Issue by asdfzxcvbn** [ChiChou/bagbak#102]
**Describe the bug**
for example, Picsart fails to dump successfully. the dumping process ends like so:

```
patch PluginKit validation
dump extensions
FATAL ERROR: session detached
reason: process-terminated
unable to dump plugins Error: Script is destroyed
Please file a bug to https://github.com/ChiChou/bagbak/issues
Error: Script is destroyed
    at onScriptDestroyed (/usr/local/lib/node_modules/bagbak/node_modules/frida/dist/script.js:125:26)
FATAL ERROR
[Error: Script is destroyed]
```

**To Reproduce**

just try dumping picsart, for example `bagbak Picsart`

**Expected behavior**

extensions get dumped correctly and the script doesnt exit.

**Screenshots**

<img width="729" alt="image" src="https://github.com/ChiChou/bagbak/assets/109937991/06fca35c-b959-479c-82a8-37dbbbcf7680">

**Desktop (please complete the following information):**
 - OS: macos mojave (same problem on linux)
 - nodejs: `node -v` - `v18.16.0`
 - frida-node: `16.0.19`
 - frida on device version: `16.0.19`
 - iOS and jailbreak version: iOS 15.7.5 w/ palera1n v2.0.0 (rootful)
 - The app you are trying to work on: Picsart

**Additional context**

**Comment by ChiChou** [comment]
v3.0.0 全部重写的架构已发布

**Comment by asdfzxcvbn** [comment]
> v3.0.0 全部重写的架构已发布

thank you, this update is amazing! i can't believe how fast it decrypts now.. there's just one issue: the directory structure of the ipa is invalid. it should be:

```
Example.ipa
├─ Payload/
│  ├─ Example.app/
│  │  ├─ ...
```

however, bagbak is currently generating it like this:

```
Example.ipa
├─ var/
│  ├─ folders/
│  │  ├─ c3/
│  │  │  ├─ .../
│  │  │  │  ├─ T/
│  │  │  │  │  ├─ bagbak/
│  │  │  │  │  │  ├─ com.example.app/
│  │  │  │  │  │  │  ├─ Payload/
│  │  │  │  │  │  │  │  ├─ ...
```

**Comment by ChiChou** [comment]
@asdfzxcvbn which host OS it is?

**Comment by asdfzxcvbn** [comment]
> @asdfzxcvbn which host OS it is?

it's an iphone 7 running iOS 14.8, dualbooted with https://github.com/dualra1n/dualra1n

**Comment by asdfzxcvbn** [comment]
> @asdfzxcvbn which host OS it is?

oh sorry i mean macos mojave
