### ISSUE TITLE
喜马拉雅9.1.39无法脱壳

### ISSUE THREAD

**Issue by shaohuihu** [ChiChou/bagbak#104]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![截屏2023-05-31 11 37 06](https://github.com/ChiChou/bagbak/assets/6970321/c67f9d1e-766e-449d-a3ee-fe86ea0d835f)

**Desktop (please complete the following information):**
 - OS: Macos 13.0.1
 - nodejs: v18.15.0
 - frida-node: 16.0.19
 - frida on device version 16.0.19
 - iOS and jailbreak version 13.3.1/iphone7
 - The app you are trying to work on com.gemd.iting

**Additional context**

**Comment by ChiChou** [comment]
v3.0.0 已全部重写
