### ISSUE TITLE
quits in shell after please be patient msg

### ISSUE THREAD

**Issue by Geczy** [ChiChou/bagbak#107]
**Describe the bug**

bagbak quits after please be patient msg

**To Reproduce**

bagbak com.christianselig.Apollo -d -f
remote root /private/var/containers/Bundle/Application/CFA00700-DD28-49CA-B724-FBF8DE140F92/Apollo.app
copy to /var/folders/d_/1vvvnjp51slbx4347nwm4qgm0000gq/T/bagbak/com.christianselig.Apollo/Payload
[info] pulling app bundle from device, please be patient

**Expected behavior**
work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu] macos 13.4
 - nodejs: [e.g. v12.18.0] v19.9.0
 - frida-node: [e.g. v12.9.6] idk what that is
 - frida on device version 16.0.19
 - iOS and jailbreak version 16.3.1
 - The app you are trying to work on `com.christianselig.Apollo`

**Additional context**

 3.0.9 bagbak

**Comment by ChiChou** [comment]
Can you please run with `DEBUG=1 DEBUG_SCP bagbak --raw -f` and paste the logs here?

**Comment by Geczy** [comment]
`zsh: command not found: DEBUG_SCP` im on macos, what do you recommend instead of debug_scp ?

**Comment by ChiChou** [comment]
> `zsh: command not found: DEBUG_SCP` im on macos, what do you recommend instead of debug_scp ?

Sorry, `DEBUG_SCP=1`. It's an environment variable too. Also better upgrade to v3.0.11 (it's not related to this issue though)

**Comment by Geczy** [comment]
```
DEBUG=1 DEBUG_SCP=1 bagbak --raw -f com.christianselig.Apollo
remote root /private/var/containers/Bundle/Application/BE0D5A55-3C4E-4E4A-AA71-7F7FACB3730E/Apollo.app
copy to .
[info] pulling app bundle from device, please be patient
```

**Comment by ChiChou** [comment]
Doesn't make sense. Even if there is an exception it should print something

**Comment by ChiChou** [comment]
I ran it on my macOS 14.0 with the same nodejs v19.9.0 but it didn't reproduce

**Comment by Geczy** [comment]
so its an issue in sshing to the ios device? where does that even happen? 

my user is `mobile` not `root` if that makes a difference?

**Comment by ChiChou** [comment]
I hardcoded root/alpine in the code so it will always be root. Besides if there is something wrong with SSH it will definitely print the reason

**Comment by Geczy** [comment]
ahh got it. funny that using the wrong user + pw combo will make this not work completely. 

its working now once i hardcoded my correct user + password

im coming from palera1n and when installing that jailbreak, they install to `mobile` and force you to setup your own password. they dont use `root:alpine` so maybe its worth having a custom .env or config file or env variables to customize this

**Comment by Geczy** [comment]
now the next issue is with commands not using `sudo` 😂 

i can hardcode change chmod to use sudo, but i wonder if tehre are other places in bagbak that require privileges? 

```js
main executable => /private/var/containers/Bundle/Application/BE0D5A55-3C4E-4E4A-AA71-7F7FACB3730E/Apollo.app/Apollo
chmod: changing permissions of '/private/var/containers/Bundle/Application/BE0D5A55-3C4E-4E4A-AA71-7F7FACB3730E/Apollo.app/Apollo': Operation not permitted
file:///Users/mgates/bagbak/index.js:84
            reject(new Error(`remote command "${cmd}" exited with code ${code}`));
                   ^

Error: remote command "chmod +xX '/private/var/containers/Bundle/Application/BE0D5A55-3C4E-4E4A-AA71-7F7FACB3730E/Apollo.app/Apollo'" exited with code 1
    at Channel.<anonymous> (file:///Users/mgates/bagbak/index.js:84:20)
    at Channel.emit (node:events:525:35)
    at Channel.doClose (/Users/mgates/bagbak/node_modules/ssh2/lib/utils.js:101:21)
    at Object.onceWrapper (node:events:627:28)
    at Channel.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v19.9.0
```

**Comment by Geczy** [comment]
you can start logging ssh errors like this

```js
  return new Promise((resolve) => {
    client
      .once('ready', () => resolve(client))
      .once('error', (error) => {
        console.error(error)
        return reject(error);
      })
      .connect({
        sock: channel,
        username: user,
        password,
      });
  });
```

add once error

**Comment by ChiChou** [comment]
> now the next issue is with commands not using `sudo` 😂
> 
> i can hardcode change chmod to use sudo, but i wonder if tehre are other places in bagbak that require privileges?
> 
> ```js
> main executable => /private/var/containers/Bundle/Application/BE0D5A55-3C4E-4E4A-AA71-7F7FACB3730E/Apollo.app/Apollo
> chmod: changing permissions of '/private/var/containers/Bundle/Application/BE0D5A55-3C4E-4E4A-AA71-7F7FACB3730E/Apollo.app/Apollo': Operation not permitted
> file:///Users/mgates/bagbak/index.js:84
>             reject(new Error(`remote command "${cmd}" exited with code ${code}`));
>                    ^
> 
> Error: remote command "chmod +xX '/private/var/containers/Bundle/Application/BE0D5A55-3C4E-4E4A-AA71-7F7FACB3730E/Apollo.app/Apollo'" exited with code 1
>     at Channel.<anonymous> (file:///Users/mgates/bagbak/index.js:84:20)
>     at Channel.emit (node:events:525:35)
>     at Channel.doClose (/Users/mgates/bagbak/node_modules/ssh2/lib/utils.js:101:21)
>     at Object.onceWrapper (node:events:627:28)
>     at Channel.emit (node:events:525:35)
>     at endReadableNT (node:internal/streams/readable:1359:12)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> 
> Node.js v19.9.0
> ```

comment line 134 of main.js out

**Comment by Geczy** [comment]
all solved, thanks for the updates
