### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mmas9689** [ChiChou/bagbak#113]
C:\Users\Mahmood>bagbak net.whatsapp.WhatsApp
[info] pulling app bundle from device, please be patient
[info] downloaded 1208 files and 430 folders
[info] app bundle downloaded
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: (NULL)
    at value (frida/runtime/core.js:229)
    at newDump (/script1.js:35)
    at apply (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:13)
    at c (frida/runtime/message-dispatcher.js:23) {
  fileName: 'frida/runtime/core.js',
  lineNumber: 229
}

Node.js v18.16.0

**Comment by ChiChou** [comment]
Can't reproduce and your thread does not provide enough environment information. Please use the issue template.
