### ISSUE TITLE
dependent dylib not found

### ISSUE THREAD

**Issue by asdfzxcvbn** [ChiChou/bagbak#115]
Before you submit the issue, please check the FAQ section in Wiki.

https://github.com/ChiChou/bagbak/wiki#faq

**Describe the bug**
when dumping parcel, bagbak errors out after the `app bundle downloaded` part. 

**To Reproduce**

`bagbak Parcel`

```
[info] pulling app bundle from device, please be patient
[info] downloaded 895 files and 289 folders
[info] app bundle downloaded
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: dlopen(/private/var/containers/Bundle/Application/A06937E0-30B1-4426-83BF-CC4D8F6E153C/Parcel.app/Extensions/Parcel App Intents Extension.appex/Parcel App Intents Extension, 0x0001): dependent dylib '/System/Library/Frameworks/AppIntents.framework/AppIntents' not found for '/private/var/containers/Bundle/Application/A06937E0-30B1-4426-83BF-CC4D8F6E153C/Parcel.app/Extensions/Parcel App Intents Extension.appex/Parcel App Intents Extension'
    at value (frida/runtime/core.js:229)
    at newDump (/script1.js:35)
    at apply (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:13)
    at c (frida/runtime/message-dispatcher.js:23) {
  fileName: 'frida/runtime/core.js',
  lineNumber: 229
}
```

**Expected behavior**

dumped successfully

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - nodejs: 16.20.0
 - frida on device version - 16.0.19
 - iOS and jailbreak version - 14.8 - palera1n
 - The app you are trying to work on - Parcel `com.mr-brightside.myParcel`

**Additional context**

**Comment by ChiChou** [comment]
https://developer.apple.com/documentation/appintents

AppIntents is only available on iOS 16.0+. The app developer set a wrong [MinimumOSVersion](https://developer.apple.com/documentation/bundleresources/information_property_list/minimumosversion), actually you are not supposed to install it at all.

Since iOS 14 allows you to remount rootfs, maybe try to put a placeholder dylib there?
