### ISSUE TITLE
用2.6.6正常，升级最新版3.0.16后砸壳报错

### ISSUE THREAD

**Issue by Prisoner-One** [ChiChou/bagbak#117]
系统是Windows11，之前一直用的2.6.6版bagbak砸壳基本没什么问题，后来换成3.0.16砸壳所有程序都报同样的错误。
手机是6s 15.7.6 palera1n有根越狱

C:\Users\nanshan>bagbak com.apple.TestFlight
[info] pulling app bundle from device, please be patient
[info] downloaded 423 files and 207 folders
[info] app bundle downloaded
[decrypt] TestFlight
chmod: cannot access '/private/var/containers/Bundle/Application/C7951298-C041-4640-A580-70E2C9ABE129/TestFlight.app/PlugIns\TestFlightServiceExtension.appex\TestFlightServiceExtension': No such file or directory
failed to execute "chmod +xX '/private/var/containers/Bundle/Application/C7951298-C041-4640-A580-70E2C9ABE129/TestFlight.app/PlugIns\TestFlightServiceExtension.appex\TestFlightServiceExtension'", exited with code 1
Failed to spawn executable at /private/var/containers/Bundle/Application/C7951298-C041-4640-A580-70E2C9ABE129/TestFlight.app/PlugIns\TestFlightServiceExtension.appex\TestFlightServiceExtension, skipping...
Warning: Unable to dump PlugIns\TestFlightServiceExtension.appex\TestFlightServiceExtension
Compress-Archive : .ipa 不是支持的存档文件格式。只有 .zip 才是支持的存档文件格式。
所在位置 行:1 字符: 1
+ Compress-Archive -Force Payload C:\Users\nanshan\com.apple.TestFlight ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (.ipa:String) [Compress-Archive]，IOException
    + FullyQualifiedErrorId : NotSupportedArchiveFileExtension,Compress-Archive

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "command exited with code 1 (null)".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v19.9.0

请教一下大佬该怎么解决这个问题，我尝试过在虚拟机ubuntu系统里使用又是一切正常。

**Comment by ChiChou** [comment]
不按模版的 issue 一律关闭
