### ISSUE TITLE
win11砸壳PlugIns里的appex报错

### ISSUE THREAD

**Issue by Prisoner-One** [ChiChou/bagbak#118]
感谢大佬及时修复win11砸壳打包问题，谢谢！！

Describe the bug
砸壳所有程序都是这个问题，用ostool查看发现appex未砸壳成功

Screenshots

![QQ截图20230624131654](https://github.com/ChiChou/bagbak/assets/71011287/ae60c09b-1fd4-45d9-a2c6-860de20594f1)

Desktop (please complete the following information):
 - OS: [windows11]
 - nodejs: [ v19.9.0]
 - frida on device version：16.0.19
 - iOS and jailbreak version：15.7.5 palera1n 有根越狱
 - 以前用2.6.6版本都是能正常砸壳appex，升级后就报错了

**Comment by Prisoner-One** [comment]
是因为这个吗？
‘’‘
Windows Compatibility
Filesystem of iOS differs from Windows. If you are running bagbak on Windows, some of the file attributes (e.g., executable bit) will be lost, thus the repacked ipa may not be able to reinstall on your phone. But it does not matter if you only indend to do static analysis.

’‘’

**Comment by Prisoner-One** [comment]
我替换了lib文件夹里的scan.js文件，然后bagbak崩了。。

```
C:\Users\nanshan>bagbak
file:///C:/Users/nanshan/AppData/Roaming/npm/node_modules/bagbak/lib/scan.js:15
    const r = new RegExp(path.sep, 'g');
              ^

SyntaxError: Invalid regular expression: /\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at file:///C:/Users/nanshan/AppData/Roaming/npm/node_modules/bagbak/lib/scan.js:15:15
    at file:///C:/Users/nanshan/AppData/Roaming/npm/node_modules/bagbak/lib/scan.js:20:3
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

Node.js v19.9.0

```

**Comment by ChiChou** [comment]
v3.0.19

**Comment by Prisoner-One** [comment]
> v3.0.19

感谢大佬修复，测试砸壳都正常了 ，谢谢
