### ISSUE TITLE
bagbak saves app files outside the .app

### ISSUE THREAD

**Issue by asdfzxcvbn** [ChiChou/bagbak#119]
**Describe the bug**
when dumping apps using `-r`, bagbak will dump app files outside the .app folder

**To Reproduce**
`bagbak -fro s Spotify`

**Expected behavior**
everything is dumped in the correct folder

**Screenshots**

![img](https://cdn.discordapp.com/attachments/1099871910155796495/1123623048243839118/image.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux (can reproduce on macos mojave)
 - nodejs: v16.20.0
 - frida on device version - v16.19.0
 - iOS and jailbreak version - iOS 14.8 + rootful palera1n
 - The app you are trying to work on - spotify - [com.spotify.client](https://apps.apple.com/app/id324684580)

**Comment by asdfzxcvbn** [comment]
i could move `Intents.strings` to the .app, but this seems to be happening as well

![img](https://cdn.discordapp.com/attachments/1099871910155796495/1123624381483057162/image.png)

**Comment by ChiChou** [comment]
Didn't reproduce here but looks like a race condition in scp module. 
Can you run with `DEBUG_SCP=1 bagbak -fro s Spotify` and give me the logs?

**Comment by asdfzxcvbn** [comment]
> `DEBUG_SCP=1 bagbak -fro s Spotify`

it looks like this only happens sometimes for some reason. i dont know why, but if it happens again i'll add more info here.

**Comment by ChiChou** [comment]
So it's definitely race condition, which don't always happen 

> > `DEBUG_SCP=1 bagbak -fro s Spotify`
> 
> 
> 
> it looks like this only happens sometimes for some reason. i dont know why, but if it happens again i'll add more info here.

**Comment by ChiChou** [comment]
I believe it should be fixed now
