### ISSUE TITLE
[feature request] quit on decrypt failure

### ISSUE THREAD

**Issue by asdfzxcvbn** [ChiChou/bagbak#125]
sometimes, apps aren't able to be decrypted by bagbak, however it attempts to continue decrypting as much as possible. i run a bot that runs on bagbak, so this actually wastes some bandwidth and time. could we get a flag (-q, for example) to quit decrypting and exit with status code 1 if a framework/appex/executable isnt able to be decrypted?

**Comment by ChiChou** [comment]
Sorry I missed out this thread. Will do that

**Comment by ChiChou** [comment]
[3.0.27](https://github.com/ChiChou/bagbak/releases/tag/v3.0.27) should have this implemented
