### ISSUE TITLE
iOS  15 使用palera1n 越狱后  使用 提示设备未越狱

### ISSUE THREAD

**Issue by Nododo** [ChiChou/bagbak#126]
me:~ $ bagbak -l
This tool requires a jailbroken 64bit iOS device

**Comment by arm64x** [comment]
On iOS device nstall frida from repo: https://build.frida.r/
Install mterminal or newterm tweak then open and run: frida-server -D

**Comment by Nododo** [comment]
> On iOS device nstall frida from repo: https://build.frida.r/ Install mterminal or newterm tweak then open and run: frida-server -D

my fault

long time no use  ahaha

thanks.
