### ISSUE TITLE
Unable to dump apps on Apple Security research device

### ISSUE THREAD

**Issue by cfossace** [ChiChou/bagbak#129]
There is an error dumping the app. 

➜  bagbak -U my.app.testing.triggerdebug.testing-app 
[info] pulling app bundle from device, please be patient

[info] app bundle downloaded
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, scandir '/var/folders/rr/n_90hxwd49gc5n3nwyrw6qdr0000gp/T/bagbak/my.app.testing.triggerdebug.testing-app/Payload/testing app.app'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/var/folders/rr/n_90hxwd49gc5n3nwyrw6qdr0000gp/T/bagbak/my.app.testing.triggerdebug.testing-app/Payload/testing app.app'
}

Node.js v18.18.2

**To Reproduce**

`bagbak -U my.app.testing.triggerdebug.testing-app `

**Expected behavior**
I expect it to dump the decrypted app, but it seems like there is a problem. 

**Desktop (please complete the following information):**
 - OS: MacOS 13.5
 - ➜ npm --version
9.8.1
➜ node --version
v18.18.2
 - frida on device version 16.1.4
 - iOS and jailbreak version Apple Security research device iOS 17 (non jailbroken, Frida installed with cryptex)

**Comment by ChiChou** [comment]
I can't find this bundle id. Are you side-loading it?

**Comment by cfossace** [comment]
Oh yeah sorry I was doing this with a test app. To confirm though, no apps work at all. They all get this same error :(

**Comment by cfossace** [comment]
It seems like frida-ios-dump has the exact same error, so I can't tell if it is maybe something Frida-side? https://github.com/AloneMonkey/frida-ios-dump/issues/180

**Comment by ChiChou** [comment]
To side load an app, the app must be already decrypted. What do you wanna implement?

**Comment by ChiChou** [comment]
I don't think it has anything to do with frida. Your ipa must have some broken symbolic link inside

**Comment by ChiChou** [comment]
> No I can't dump any apps with frida. I am not sideloading apps, I am dumping app store apps. I was just testing the dumping with a sideloaded app to see if that would help, but that didn't work either.

but same error for store apps?

**Comment by cfossace** [comment]
Yeah, even App Store apps get the same error. It seems like all apps are having this problem :(
