### ISSUE TITLE
[Error: Unable to access process with pid 1 from the current user account]

### ISSUE THREAD

**Issue by Mabisi** [ChiChou/bagbak#137]
Before you submit the issue, please check the FAQ section in Wiki: https://github.com/ChiChou/bagbak/wiki#faq
Then delete this section.

bagbak -l 可以正常运行出现列表 
SIP也关闭了

![image](https://github.com/ChiChou/bagbak/assets/19968269/435b5a3c-6fd8-4d43-a1f4-fc141a652589)

**Desktop (please complete the following information):**
 - OS: MACOS 12.6.1 
 - nodejs: V18.12.1
 - frida on device version 16.1.11
 - iOS and jailbreak version 16.3
 - The app you are trying to work on [e.g. com.example.app, better with AppStore link]

**Additional context**

**Comment by Mabisi** [comment]
测试  bagbakV3.0.27版本可以正常使用

**Comment by hyp-real** [comment]
我和你问题相似，我是Error: Unable to access process with pid xxx from the current user account
Desktop (please complete the following information):

OS: MacOS 14.1
nodejs: V20.11.1
frida on device version: 16.2.1
iOS and jailbreak version: iOS 16.5, Dopamine rootless
The app you are trying to work on: any app
