### ISSUE TITLE
Unable to access process with pid 1

### ISSUE THREAD

**Issue by karelpak1** [ChiChou/bagbak#138]
! most likely duplicate with #137 

**Describe the bug**
[Error: Unable to access process with pid 1 from the current user account]

**To Reproduce**
Run frida-server and try to bagbak app

**Expected behavior**
Pulling and decrypting selected app (in this case WoT Blitz)

**Screenshots**
![obrázek_2024-01-26_234932683](https://github.com/ChiChou/bagbak/assets/57904835/b3013866-c136-4db8-83ff-a542519e6b95)

**Laptop:**
 - OS: macOS Monterey (12.7.3) - OpenCore
 - nodejs: v20.11.0
 - fruity-frida 0.0.16
 - iPad Pro 2017, iPadOS 17.1.1 rootless (via palera1n)
 - The app I am trying to work on net.wargaming.wotblitz (WoT Blitz)
 - bagbak: 3.2.2

**Additional context**
In SSH Environment is set login mobile/alpine, because root/alpine does't work.

**Comment by ChiChou** [comment]
dup #137
