### ISSUE TITLE
Unable to access process with pid xxxxx from the current user account

### ISSUE THREAD

**Issue by hyp-real** [ChiChou/bagbak#139]
bagbak -l 可以正常运行出现列表
SIP也关闭了
Unable to access process with pid xxxxx from the current user account

**Screenshots**
![图像](https://github.com/ChiChou/bagbak/assets/63187103/32dc7071-4c67-45af-beca-264bca2a1bf5)

**Desktop (please complete the following information):**
 - OS: MacOS 14.1
 - nodejs: V20.11.1
 - frida on device version: 16.2.1
 - iOS and jailbreak version iOS 16.5 with Dopamine 2.0.5
 - The app you are trying to work on: any app
**Additional context**

**Comment by Prisoner-One** [comment]
我也遇到同样问题，多巴胺越狱好像还不支持，等大佬更新吧

**Comment by hyp-real** [comment]
> 我也遇到同样问题，多巴胺越狱好像还不支持，等大佬更新吧

耐心等待，静候佳音吧

**Comment by ChiChou** [comment]
主题重复 #137
