### ISSUE TITLE
iOS 15 changed XPC schema

### ISSUE THREAD

**Issue by Prisoner-One** [ChiChou/bagbak#141]
Describe the bug
多巴胺2.0.9越狱，砸壳app还是报错

Screenshots
<img width="880" alt="截屏2024-03-03 12 49 20" src="https://github.com/ChiChou/bagbak/assets/71011287/f983721b-b0b9-4220-a844-c3546263c0e2">

Desktop (please complete the following information):
 - OS: mac  ,  win11  ,  ubuntu(vm)
 - nodejs: v20.11.0
 - frida on device version：frida 16.21.1
 - iOS and jailbreak version: ios15.8.1  Dopamine2.0.9 iphone6s
 - The app you are trying to work on ：Shadowrocket ， telegram

**Comment by ChiChou** [comment]
Shadowrock 是收费应用我测不了

Telegram 在我这里可以

**Comment by Prisoner-One** [comment]
> Shadowrock 是收费应用我测不了
> 
> Telegram 在我这里可以

大佬，我砸壳所有的app都报错
Error: pids is null
    at implementation (/script1.js:116)
    at call (native)
    at f (<input>:1) {
  fileName: '/script1.js',
  lineNumber: 116
手机是ihone6s ，系统15.8.1 ，多巴胺2.0.9越狱， 电脑是mac 14.1.1 (23B81) 安装的bagbak3.3.0 。
以前用palera1n砸壳一直没问题 ，换多巴胺就报错这个，这个报错是我哪里设置有问题吗？ 
麻烦指教一下 ，非常感谢！

**Comment by Prisoner-One** [comment]
> Shadowrock 是收费应用我测不了
> 
> Telegram 在我这里可以

不知道debug是不是这么用的 但是应该可以给你参考一下

nanshan@NanshanMac-Pro ~ % DEBUG=1 bagbak QQ
remote root /private/var/containers/Bundle/Application/3FB05C76-5E6C-49B6-91E7-52986C54ABFC/QQ.app
copy to /var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload
[info] pulling app bundle from device, please be patient
[info] downloaded 12862 files and 734 folders
[info] app bundle downloaded
mach-o info /var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/Frameworks/QQStartup.framework/QQStartup {
  path: '/var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/Frameworks/QQStartup.framework/QQStartup',
  type: 6,
  encryptInfo: { offset: 16384, size: 23674880, id: 0 },
  encCmdOffset: 3488
}
mach-o info /var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/Frameworks/QQStartupOnLogin.framework/QQStartupOnLogin {
  path: '/var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/Frameworks/QQStartupOnLogin.framework/QQStartupOnLogin',
  type: 6,
  encryptInfo: { offset: 16384, size: 16941056, id: 0 },
  encCmdOffset: 3504
}
mach-o info /var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/Frameworks/TXSoundTouch.framework/TXSoundTouch {
  path: '/var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/Frameworks/TXSoundTouch.framework/TXSoundTouch',
  type: 6,
  encryptInfo: { offset: 16384, size: 16384, id: 0 },
  encCmdOffset: 1328
}
mach-o info /var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/Frameworks/UE4.framework/UE4 {
  path: '/var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/Frameworks/UE4.framework/UE4',
  type: 6,
  encryptInfo: { offset: 16384, size: 50577408, id: 0 },
  encCmdOffset: 3104
}
mach-o info /var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/Frameworks/WeAppCoreSDK.framework/WeAppCoreSDK {
  path: '/var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/Frameworks/WeAppCoreSDK.framework/WeAppCoreSDK',
  type: 6,
  encryptInfo: { offset: 16384, size: 22609920, id: 0 },
  encCmdOffset: 3408
}
mach-o info /var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/Frameworks/andromeda.framework/andromeda {
  path: '/var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/Frameworks/andromeda.framework/andromeda',
  type: 6,
  encryptInfo: { offset: 16384, size: 1966080, id: 0 },
  encCmdOffset: 2520
}
mach-o info /var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/Frameworks/ilink.framework/ilink {
  path: '/var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/Frameworks/ilink.framework/ilink',
  type: 6,
  encryptInfo: { offset: 16384, size: 8060928, id: 0 },
  encCmdOffset: 2912
}
mach-o info /var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/PlugIns/QQBroadCast.appex/QQBroadCast {
  path: '/var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/PlugIns/QQBroadCast.appex/QQBroadCast',
  type: 2,
  encryptInfo: { offset: 176128, size: 4096, id: 1 },
  encCmdOffset: 2912
}
mach-o info /var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/PlugIns/QQNotificationContent.appex/QQNotificationContent {
  path: '/var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/PlugIns/QQNotificationContent.appex/QQNotificationContent',
  type: 2,
  encryptInfo: { offset: 65536, size: 4096, id: 1 },
  encCmdOffset: 3072
}
mach-o info /var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/PlugIns/QQNotificationService.appex/QQNotificationService {
  path: '/var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/PlugIns/QQNotificationService.appex/QQNotificationService',
  type: 2,
  encryptInfo: { offset: 122880, size: 4096, id: 1 },
  encCmdOffset: 3232
}
mach-o info /var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/PlugIns/QQShare.appex/QQShare {
  path: '/var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/PlugIns/QQShare.appex/QQShare',
  type: 2,
  encryptInfo: { offset: 131072, size: 4096, id: 1 },
  encCmdOffset: 2992
}
mach-o info /var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/PlugIns/QQWidgetExtension.appex/QQWidgetExtension {
  path: '/var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/PlugIns/QQWidgetExtension.appex/QQWidgetExtension',
  type: 2,
  encryptInfo: { offset: 274432, size: 4096, id: 1 },
  encCmdOffset: 2736
}
mach-o info /var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/QQ {
  path: '/var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/QQ',
  type: 2,
  encryptInfo: { offset: 218886144, size: 4096, id: 1 },
  encCmdOffset: 5472
}
encrypted binaries Map(6) {
  'com.tencent.mqq' => {
    dylibs: [
      [Array], [Array],
      [Array], [Array],
      [Array], [Array],
      [Array], [Array]
    ],
    executable: 'QQ'
  },
  'com.tencent.mqq.BroadCast' => {
    dylibs: [ [Array] ],
    executable: 'PlugIns/QQBroadCast.appex/QQBroadCast'
  },
  'com.tencent.mqq.notificationContent' => {
    dylibs: [ [Array] ],
    executable: 'PlugIns/QQNotificationContent.appex/QQNotificationContent'
  },
  'com.tencent.mqq.notificationService' => {
    dylibs: [ [Array] ],
    executable: 'PlugIns/QQNotificationService.appex/QQNotificationService'
  },
  'com.tencent.mqq.ShareExtension' => { dylibs: [ [Array] ], executable: 'PlugIns/QQShare.appex/QQShare' },
  'com.tencent.mqq.qqwidgetapp' => {
    dylibs: [ [Array] ],
    executable: 'PlugIns/QQWidgetExtension.appex/QQWidgetExtension'
  }
}
pid => 17234
main executable => /var/folders/j9/4x6s_svd1xv8_k6ykdvmw6kr0000gn/T/bagbak/com.tencent.mqq/Payload/QQ.app/QQ
Failed to attach to pid 17234, skipping...
Warning: Unable to dump Frameworks/QQStartup.framework/QQStartup
Frameworks/QQStartupOnLogin.framework/QQStartupOnLogin
Frameworks/TXSoundTouch.framework/TXSoundTouch
Frameworks/UE4.framework/UE4
Frameworks/WeAppCoreSDK.framework/WeAppCoreSDK
Frameworks/andromeda.framework/andromeda
Frameworks/ilink.framework/ilink
QQ
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: pids is null
    at implementation (/script1.js:116)
    at call (native)
    at f (<input>:1) {
  fileName: '/script1.js',
  lineNumber: 116
}

Node.js v20.11.0

**Comment by hyp-real** [comment]
和我问题一模一样，甚至连日志都一样

**Comment by ChiChou** [comment]
ShadowRocket 是另一个问题，暂时没有办法解决

**Comment by Prisoner-One** [comment]
感谢大佬更新修复！
