### ISSUE TITLE
部分plugins无法解密

### ISSUE THREAD

**Issue by lengyu1983** [ChiChou/bagbak#142]
测试应用-轻颜相机
测试设备-iphone 12
设备系统-14.4.1
报错内容-Failed to attach to pid 7475, skipping...
Warning: Unable to dump PlugIns/Widget.appex/Widget

**Comment by ChiChou** [comment]
不按模版写也不给足够多信息

**Comment by Nanshan-Q** [comment]
> 不按模版写也不给足够多信息

我也遇到了同样的问题，麻烦大佬帮忙看看，谢谢！
![屏幕截图 2024-03-06 122716](https://github.com/ChiChou/bagbak/assets/71011287/1a0e2a6f-27b3-46d1-9ea4-297cc24a28c1)
![屏幕截图 2024-03-06 122727](https://github.com/ChiChou/bagbak/assets/71011287/eb3e78ed-531f-40c6-bfa0-455fae183fd9)
![屏幕截图 2024-03-11 130433](https://github.com/ChiChou/bagbak/assets/71011287/d36c4d71-1544-43cb-b29d-c7a9cb1bb226)
![屏幕截图 2024-03-11 130602](https://github.com/ChiChou/bagbak/assets/71011287/ef27f095-d9d9-460b-80f1-56ae723df0c8)
![屏幕截图 2024-03-11 130654](https://github.com/ChiChou/bagbak/assets/71011287/06b7898e-1e61-409f-b36a-4eb4c8e857e6)


 - OS: win11
 - nodejs: v20.11.1
 - frida on device version：iphone6s 
 - iOS and jailbreak version：ios15.8.1 bagbak3.3.1  Dopamine2.0.11
