### ISSUE TITLE
The dumped IPA file is not in the decrypted state

### ISSUE THREAD

**Issue by hebinary** [ChiChou/bagbak#148]
dopamine : 2.1.4
ios :  15.6 
iphone :  12(19G71)
frida: 16.2.5

The dumped IPA file is not in the decrypted state，Every app can dump files, but it's all encrypted

**Comment by yodaluca23** [comment]
Yep, this is happening to me too, TrollStore gives this error, Install error 180, log, https://pastebin.com/raw/b1hr14pH

**Comment by hebinary** [comment]
> Same question for me. Chichou said this is due to a bug in Frida, which he can't fix.

But it can be done on lower versions of phones, or it can be done with a jailbreak root

**Comment by hebinary** [comment]
> Yep, this is happening to me too, TrollStore gives this error, Install error 180, log, https://pastebin.com/raw/b1hr14pH

I don't report any errors, everything is normal, The dump is still encrypted

**Comment by hebinary** [comment]
> Yep, this is happening to me too, TrollStore gives this error, Install error 180, log, https://pastebin.com/raw/b1hr14pH

Frida just updated, see if it works

**Comment by ChiChou** [comment]
@hebinary I have no Domapine to test it. In the latest version if any error occurred during the process, it will abort immediately

**Comment by LaiKash** [comment]
> @hebinary I have no Domapine to test it. In the latest version if any error occurred during the process, it will abort immediately instead of giving undecrypted output

Now I read this bug, related to https://github.com/ChiChou/bagbak/issues/143#issuecomment-2247607848

I can help if needed.

**Comment by mtdlewald** [comment]
Hi, I want to add this seems to occur on later versions of bagbak (3.3.2) even on a palera1n device. When I dump the same app on my macbook it is always encrypted, but on my linux machine with an older version (3.0.22) it is decrypted.

**Comment by ChiChou** [comment]
Dopamine support coming soon
