### ISSUE TITLE
triggerUncaughtException(err, true /* fromPromise */);

### ISSUE THREAD

**Issue by itsmylife44** [ChiChou/bagbak#150]
[decrypt] Frameworks/widevine_cdm_secured_ios.framework/widevine_cdm_secured_ios
[decrypt] PlugIns/IntentsExtension.appex/IntentsExtension
[decrypt] PlugIns/WidgetExtension.appex/WidgetExtension

STDERR: node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Error: Unexpected early end-of-stream]

Node.js v20.17.0

bagbak --version
4.0.1

**Comment by ChiChou** [comment]
A known race condition issue, retry the same command

And issues not following the template will be closed
