### ISSUE TITLE
Can not install bagbak

### ISSUE THREAD

**Issue by sangcx5** [ChiChou/bagbak#153]
I run "npm install -g bagbak" and get this log. please help

`npm ERR! code 1
npm ERR! path /Users/user/.npm-packages/lib/node_modules/bagbak/node_modules/frida
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! Downloading toolchain 20240913...
npm ERR! Extracting toolchain...
npm ERR! Downloading SDK 20240913 for macos-arm64...
npm ERR! Extracting SDK...
npm ERR! The Meson build system
npm ERR! Version: 1.4.99
npm ERR! Source dir: /Users/user/.npm-packages/lib/node_modules/bagbak/node_modules/frida
npm ERR! Build dir: /Users/user/.npm-packages/lib/node_modules/bagbak/node_modules/frida/build
npm ERR! Build type: native build
npm ERR! Program python3 found: YES (/opt/homebrew/bin/python3)
npm ERR! Project name: frida-node
npm ERR! Project version: 16.5.2
npm ERR! C++ compiler for the host machine: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-macos11.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk (clang 16.0.0 "Apple clang version 16.0.0 (clang-1600.0.26.3)")
npm ERR! C++ linker for the host machine: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-macos11.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk ld64 classic  PROJECT:ld64
npm ERR! Host machine cpu family: aarch64
npm ERR! Host machine cpu: aarch64
npm ERR! Program strip found: YES
npm ERR! Program node found: YES (/usr/local/bin/node)
npm ERR! Program npm found: YES (/usr/local/bin/npm)
npm ERR! Program python3 found: YES (/opt/homebrew/opt/python@3.12/bin/python3.12)
npm ERR! Message: Fetching ABI bits
npm ERR! 
npm ERR! meson.build:55:11: ERROR: Command `/opt/homebrew/opt/python@3.12/bin/python3.12 /Users/user/.npm-packages/lib/node_modules/bagbak/node_modules/frida/scripts/fetch-abi-bits.py node '' mac arm64 /usr/local/bin/node /usr/local/bin/npm /Users/user/.npm-packages/lib/node_modules/bagbak/node_modules/frida/build` failed with status 1.
npm ERR! 
npm ERR! A full log can be found at /Users/user/.npm-packages/lib/node_modules/bagbak/node_modules/frida/build/meson-logs/meson-log.txt
npm ERR! prebuild-install warn install No prebuilt binaries found (target=21.5.0 runtime=node arch=arm64 libc= platform=darwin)
npm ERR! Command '['/opt/homebrew/opt/python@3.12/bin/python3.12', '/Users/user/.npm-packages/lib/node_modules/bagbak/node_modules/frida/releng/meson/meson.py', 'setup', '-Dprefix=/usr/local', '-Ddefault_library=static', '-Doptimization=s', '-Db_ndebug=true', '-Dstrip=true', '--native-file=/Users/user/.npm-packages/lib/node_modules/bagbak/node_modules/frida/build/frida-macos-arm64.txt', PosixPath('/Users/user/.npm-packages/lib/node_modules/bagbak/node_modules/frida/build')]' returned non-zero exit status 1.
npm ERR! make: *** [all] Error 1

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2024-09-28T02_11_05_606Z-debug-0.log`

**Comment by ChiChou** [comment]
Please read docs
