### ISSUE TITLE
bagbak -l 之后,iPhone重启

### ISSUE THREAD

**Issue by pxx917144686** [ChiChou/bagbak#155]
1、Node.js 版本 v22.9.0
2、frida:Mac上与iOS上,版本一致.
3、打开SSH
4、执行:bagbak -l  显示系统APP.  然后iPhone很快会重启!
5、iOS系统iOS14.4.1 越狱工具taurine

**Comment by ChiChou** [comment]
https://github.com/frida/frida/issues/2643

**Comment by ChiChou** [comment]
试试随便用 frida 干点什么看，会不会崩

**Comment by pxx917144686** [comment]
> 试试随便用 frida 干点什么看，会不会崩

ios14.4.1
taurine 1.1.7-3
Frida 15.1.8
Mac执行: frida-ls-devices ——> 正常
Mac执行: frida-ps -U ——> 成功连接! 之后iPhone重新启动
