### ISSUE TITLE
unable to dump plugins null: null

### ISSUE THREAD

**Issue by hduarte** [ChiChou/bagbak#22]
Env:
- iOS 12.4
- unc0ver 3.7.0~b3
- Frida 12.7.16

WhatsApp was not found by its name.
```
root@kali:~/ios/bagbak# ./go.js WhatsApp 
FATAL ERROR
Error: Unable to find app: WhatsApp
    at Device.run (/root/ios/bagbak/lib/device.js:44:13)
    at async main (/root/ios/bagbak/go.js:365:21)
```
The dump fails at the plugins extraction with the exception: **unable to dump plugins null: null**
```
root@kali:~/ios/bagbak# ./go.js net.whatsapp.WhatsApp
app root: /var/containers/Bundle/Application/0A6F0A27-4B0F-40D8-8880-3F6B6D687460/WhatsApp.app
dump main app
download WhatsApp
████████████████████████████████████████ | 100% | 21.22Mib/21.22Mib
fetching decrypted data
████████████████████████████████████████ | 100% | 16.73Mib/16.73Mib
download Core
████████████████████████████████████████ | 100% | 11.22Mib/11.22Mib
fetching decrypted data
████████████████████████████████████████ | 100% | 7.91Mib/7.91Mib
patch PluginKit validation
dump extensions
unable to dump plugins null: null
Congrats!
open dump/net.whatsapp.WhatsApp/Payload
```
The same happens for 1Password and Twitter.

**Comment by ChiChou** [comment]
Your issues are really a mess.
This issue has actually two different topic, one of which is the same as #23.

**Comment by ChiChou** [comment]
WhatsApp is not my fault. Please notice that there is actually a blank space right before "W"

![image](https://user-images.githubusercontent.com/2802045/68279749-0caa8500-00af-11ea-8219-5195eaf71eb5.png)


```
➜  /tmp bagbak -l | grep WhatsApp
│   40    │      'net.whatsapp.WhatsApp'      │  '‎WhatsApp'   │  0   │
```

You can use bundle id instead, or copy-paste like this:

![image](https://user-images.githubusercontent.com/2802045/68279795-264bcc80-00af-11ea-9cb6-c8fdf1ca0b9d.png)
