### ISSUE TITLE
作者您好，我安装出现问题

### ISSUE THREAD

**Issue by League2EB** [ChiChou/bagbak#26]
安装完毕后执行得到这个

![](https://i.loli.net/2019/12/03/CWZce9k4LOtEd2M.png)

请问我该怎么办？

**Comment by ChiChou** [comment]
1. 使用 Long Term Support 版本
2. 尽量挂代理
3. `npm uninstall -g bagbak; npm install -g bagbak`

**Comment by League2EB** [comment]
感谢您迅速的回复我
什么是Long Term Support 版本？

**Comment by ChiChou** [comment]
LTS 就是 node.js 的长期支持版，目前是 12.13.1 LTS
如果高于这个版本，可能会无法获取预编译二进制包

**Comment by League2EB** [comment]
> LTS 就是 node.js 的长期支持版，目前是 12.13.1 LTS
> 如果高于这个版本，可能会无法获取预编译二进制包

按照您说的我去安装的LTS 
然后开始导出应用，但仍然有错误

![](https://i.loli.net/2019/12/03/cB5DUtaOYpfgAi1.png)


另外这三个选项该怎么使用可以提供说明吗？

```
  -h, --host <host>      hostname
  -u, --uuid <uuid>      uuid of USB device
  -o, --output <output>  output directory
```

**Comment by ChiChou** [comment]
1. host 是 TCP 连接局域网设备用的
2. uuid 是插了多个 USB 设备之后指定其中一个

一般用不到

output 这个字面已经很清楚了吧，输出目录

**Comment by ChiChou** [comment]
> 然后开始导出应用，但仍然有错误
> 
> ![](https://camo.githubusercontent.com/d92f380bfc1e50982ecb1eafe57716901172b608/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31322f30332f634235445574614f597066674169312e706e67)
> 

这个应用在我这里没有遇到问题，但我还是提交了一个新版本先检查 bundle 是否为空
