### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by trc19930224** [ChiChou/bagbak#27]
![image](https://user-images.githubusercontent.com/16643780/70492121-4b17e180-1b3e-11ea-97e1-dc95de42ea21.png)
先感谢作者的热心分享。此工具安装成功后一直提示图上所示错误，我是操作步骤有问题还是遗漏了啥环节呢，劳烦指点下，谢谢

**Comment by ChiChou** [comment]
> node.js Latest LTS (Long Term Support)

当前最新的稳定版 node.js 是 12.13.1 LTS
