### ISSUE TITLE
Needs to dump all the dylibs/Frameworks.

### ISSUE THREAD

**Issue by rainyx** [ChiChou/bagbak#28]
### **ISSUE:**

Some dylibs/Frameworks defined in LC_LOAD_DYLIB load command,  but not load immediately after the App launched.

In this case, bagbak won't dumps these dylibs/Frameworks. If we launch the dumped App,  it will crashes because of the DYLD can't find the lost images.

**Crash log:**

> Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Library not loaded: @rpath/libswiftCore.dylib | Referenced from: /var/containers/Bundle/Application/7B61E41D-D6A6-4783-963B-07BB2616044B/XXX.app/XXX | Reason: image not found

### **How to fix:**
1. Create the dylib with following content.

```
// File: loader.cpp
#include <mach-o/loader.h>
#include <mach-o/dyld.h>
#include <dlfcn.h>
__attribute__((constructor)) void LibInit() {
	mach_header_64* mh = (mach_header_64*)_dyld_get_image_header(0);
	load_command* lc = (load_command*)(mh + 1);
	uint32_t ncmds = mh->ncmds;
	while (ncmds--) {
		if (lc->cmd == LC_LOAD_DYLIB) {
			dylib_command* dylibLc = (dylib_command*)lc;
			const char* name = (char*)lc + dylibLc->dylib.name.offset;
			dlopen(name, RTLD_GLOBAL | RTLD_LAZY);
		}
		lc = (load_command*)((char*)lc + lc->cmdsize);
	}
}
```

2. Inject the dylib into the App and launch it.
3. Run bagbak, all dylibs/Frameworks will be dumped.

Can you integrate this function into bagbak? Thanks.🍺

**Comment by ChiChou** [comment]
Can you give me the test case? Which App can I reproduce it on

**Comment by rainyx** [comment]
> Can you give me the test case? Which App can I reproduce it on

App:
千牛(v7.7.0) in AppStore.

Device:
iPhone 6s (jailbroken via unc0ver 3.7.0-b3)

**Comment by ChiChou** [comment]
Those swift runtime are located in `/usr/lib/swift/`, which should not be intergrated to the package

**Comment by ChiChou** [comment]
Are you reinstalling the app on another device?

**Comment by ChiChou** [comment]
Can you try this branch?
https://github.com/ChiChou/bagbak/tree/warmup

**Comment by rainyx** [comment]
> Those swift runtime libs are located in `/usr/lib/swift/`, which should not be intergrated to the package

If the ‘Always Embed Swift Standard Libraries’ is enabled, DYLD loads swift libraries from @rpath of the App main bundle rather than /use/lib/swift/.

**Comment by rainyx** [comment]
> Are you reinstalling the app on another device?

Nope.

**Comment by rainyx** [comment]
> Can you try this branch?
> https://github.com/ChiChou/bagbak/tree/warmup

Thank you. I’ll try later.

**Comment by ChiChou** [comment]
@rainyx 所以结果呢
