### ISSUE TITLE
是不是不兼容 macOS 10.15.3, nodejs v12.15.0

### ISSUE THREAD

**Issue by azureplus** [ChiChou/bagbak#31]
是不是不兼容 macOS 10.15.3, nodejs v12.15.0?

**Comment by azureplus** [comment]
prebuild-install WARN install unexpected end of file
gyp: binding.gyp not found (cwd: /usr/local/lib/node_modules/bagbak/node_modules/frida) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/bagbak/node_modules/frida
gyp ERR! node -v v12.15.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@12.8.10 install: `prebuild-install || node-gyp rebuild`

**Comment by ChiChou** [comment]
`npm install frida --verbose`

等到输出类似如下内容
```
prebuild-install info looking for cached prebuild @ /Users/用户名/.npm/_prebuilds/93b394-frida-v12.8.10-node-v72-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/frida/frida/releases/download/12.8.10/frida-v12.8.10-node-v72-darwin-x64.tar.gz
```

挂代理把对应 url 下载到 `/Users/用户名/.npm/_prebuilds/....tar.gz`

重新 `npm install -g bagbak`

**Comment by shitizen-x** [comment]
也遇到这个错误，按方法重试也不行

**Comment by shitizen-x** [comment]
prebuild-install WARN install unexpected end of file
gyp: binding.gyp not found (cwd: /usr/local/lib/node_modules/bagbak/node_modules/frida) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/bagbak/node_modules/frida
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@12.9.2 install: `prebuild-install || node-gyp rebuild`

**Comment by ChiChou** [comment]
@shitizen-x `prebuild-install WARN install unexpected end of file`  就是说你下回来的文件就是坏的

**Comment by Cameudis** [comment]
> `npm install frida --verbose`
> 
> 等到输出类似如下内容
> 
> ```
> prebuild-install info looking for cached prebuild @ /Users/用户名/.npm/_prebuilds/93b394-frida-v12.8.10-node-v72-darwin-x64.tar.gz
> prebuild-install http request GET https://github.com/frida/frida/releases/download/12.8.10/frida-v12.8.10-node-v72-darwin-x64.tar.gz
> ```
> 
> 挂代理把对应 url 下载到 `/Users/用户名/.npm/_prebuilds/....tar.gz`
> 
> 重新 `npm install -g bagbak`

我也遇到这个错误了，补充一个Linux上的额外注意点 :)
全局装bagbak的时候如果用的是 `sudo npm install bagbak -g`，那么需要 `sudo npm install frida --verbose` 来查看真正的prebuild缓存路径，应该是位于 `/root/.npm/_prebuilds` 之下（而不是 `/home/用户名/.npm/_prebuilds/`）
