### ISSUE TITLE
can't run utility

### ISSUE THREAD

**Issue by lscsg** [ChiChou/bagbak#33]
/root/bagbak/go.js:28
  session = ''
          ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by ChiChou** [comment]
Your nodejs runtime version is obsoleted.

As I said, you should install

> node.js Latest LTS (Long Term Support)

**Comment by lscsg** [comment]
I installed at LTS version see below, now I can't install it. 

2125 verbose lifecycle frida@12.8.10~install: unsafe-perm in lifecycle false
2126 verbose lifecycle frida@12.8.10~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/lib/node_modules/bagbak/node_modules/frida/node_modules/.bin:/usr/lib/node_modules/bagbak/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2127 verbose lifecycle frida@12.8.10~install: CWD: /usr/lib/node_modules/bagbak/node_modules/frida
2128 silly lifecycle frida@12.8.10~install: Args: [ '-c', 'prebuild-install || node-gyp rebuild' ]
2129 silly lifecycle frida@12.8.10~install: Returned: code: 1  signal: null
2130 info lifecycle frida@12.8.10~install: Failed to exec install script
2131 timing action:install Completed in 344ms
2132 verbose unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
2133 timing stage:rollbackFailedOptional Completed in 64ms
2134 timing stage:runTopLevelLifecycles Completed in 2548ms
2135 verbose stack Error: frida@12.8.10 install: `prebuild-install || node-gyp rebuild`
2135 verbose stack Exit status 1
2135 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
2135 verbose stack     at EventEmitter.emit (events.js:223:5)
2135 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2135 verbose stack     at ChildProcess.emit (events.js:223:5)
2135 verbose stack     at maybeClose (internal/child_process.js:1021:16)
2135 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
2136 verbose pkgid frida@12.8.10
2137 verbose cwd /root/bagbak
2138 verbose Linux 5.4.0-kali3-amd64
2139 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "bagbak"
2140 verbose node v12.15.0
2141 verbose npm  v6.13.4
2142 error code ELIFECYCLE
2143 error errno 1
2144 error frida@12.8.10 install: `prebuild-install || node-gyp rebuild`
2144 error Exit status 1
2145 error Failed at the frida@12.8.10 install script.
2145 error This is probably not a problem with npm. There is likely additional logging output above.
2146 verbose exit [ 1, true ]
