### ISSUE TITLE
Failed to patch pkd on Unc0ver 13.3

### ISSUE THREAD

**Issue by mtshare** [ChiChou/bagbak#34]
Hello,
I'm trying to dump an app but it fails.
Here is my configuration:
• iPhone 11 Pro Max
• iOS 13.3
• Unc0ver jailbreak (v4.2.1)

Here is the error:
```
.....
download ...ication/8DB3A365-FF73-48C1-A371-4C3FC4017198/Video.app/EVDTransitionGlitch_5.mp4
download ...iners/Bundle/Application/8DB3A365-FF73-48C1-A371-4C3FC4017198/Video.app/Fade.gif
patch PluginKit validation
FATAL ERROR
[Error: Unexpected error while starting thread (act_set_state returned '(os/kern) protection failure')]
```

**Comment by ChiChou** [comment]
This should be process injection failure for frida. Unfortunately I don't have an A13 device to test

**Comment by ChiChou** [comment]
If you don't need to dump AppExtensions, upgrade to `bagbak@1.4.3` and use `--no-extension` to skip it

https://github.com/ChiChou/bagbak/commit/c97ad26c64e42f9e56abcf8a30b5cdc7d1e68325

**Comment by Co2333** [comment]
Fixed in re.frida.server64 12.9.4. There is now an A12+ only version available from offcial Cydia repo. We should close this issue now.

**Comment by ChiChou** [comment]
@mtshare does it work now?
