### ISSUE TITLE
cannot create ipa on windows 

### ISSUE THREAD

**Issue by appengine8848** [ChiChou/bagbak#38]
the output bin file size same as origin,but MD5 hash changed, I thought it should be smaller than origin, 

is this correct ? 

then I use otool -l Chrome | grep crypt its cryptid is 0, so I'm confused now.

and I using: bagbak Chrome -n -z 
![1](https://user-images.githubusercontent.com/2500652/78206764-4baffb80-74d2-11ea-9812-063b62a7e5ee.png)

**Comment by ChiChou** [comment]
在 Windows 上增加 PowerShell 创建压缩包支持
