### ISSUE TITLE
 Incompatible Mach-O image 

### ISSUE THREAD

**Issue by LiuSky** [ChiChou/bagbak#44]
<img width="270" alt="截屏2020-06-03 上午9 11 03" src="https://user-images.githubusercontent.com/3087745/83584604-3874e700-a57a-11ea-9d05-5e90a4736679.png">
打扰下，这个要如何解决？

**Comment by ChiChou** [comment]
https://github.com/frida/frida-gum/blob/5dc34ad321f3c52c0/gum/gumdarwinmodule.c#L2164
frida 内部抛的错误，但我想知道你现在解决了没有
