### ISSUE TITLE
v8::ToLocalChecked Empty MaybeLocal.

### ISSUE THREAD

**Issue by Co2333** [ChiChou/bagbak#45]
```
app root: /var/containers/Bundle/Application/EE4C4538-1BA0-4590-A646-32FCA96F6269/______-iOS.app
dump main app
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: 0x100bc9ae7 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x10008186d node::FatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x1000819d6 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x10018505c v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/bin/node]
 5: 0x1068135b5  [/usr/local/lib/node_modules/bagbak/node_modules/frida/build/Release/frida_binding.node]
 6: 0x10680eafa  [/usr/local/lib/node_modules/bagbak/node_modules/frida/build/Release/frida_binding.node]
 7: 0x10680260d  [/usr/local/lib/node_modules/bagbak/node_modules/frida/build/Release/frida_binding.node]
 8: 0x1001d19c2 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
 9: 0x1001d104c v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
10: 0x1001d0870 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
11: 0x100754319 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
12: 0x1006ece18 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
13: 0x1006ece18 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]

```

**Comment by ChiChou** [comment]
Internal error of frida-node and no enough context to reproduce

**Comment by Jacky-LinPeng** [comment]
> error

I have the same problem!
 How to solve it? 
My Node.js version is V12.18.0, & iOS 11.2.2

**Comment by Jacky-LinPeng** [comment]
> app root: /var/containers/Bundle/Application/EE4C4538-1BA0-4590-A646-32FCA96F6269/______-iOS.app
> dump main app
> FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
>  1: 0x100bc9ae7 node::Abort() (.cold.1) [/usr/local/bin/node]
>  2: 0x10008186d node::FatalError(char const*, char const*) [/usr/local/bin/node]
>  3: 0x1000819d6 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
>  4: 0x10018505c v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/bin/node]
>  5: 0x1068135b5  [/usr/local/lib/node_modules/bagbak/node_modules/frida/build/Release/frida_binding.node]
>  6: 0x10680eafa  [/usr/local/lib/node_modules/bagbak/node_modules/frida/build/Release/frida_binding.node]
>  7: 0x10680260d  [/usr/local/lib/node_modules/bagbak/node_modules/frida/build/Release/frida_binding.node]
>  8: 0x1001d19c2 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
>  9: 0x1001d104c v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
> 10: 0x1001d0870 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
> 11: 0x100754319 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
> 12: 0x1006ece18 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
> 13: 0x1006ece18 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]

I have the same problem!
How to solve it?
My Node.js version is V12.18.0, & iOS 11.2.2

**Comment by Jacky-LinPeng** [comment]
解决方案是？求大佬指导...

**Comment by ChiChou** [comment]
@Co2333 @Jacky-LinPeng npm install the latest version
