### ISSUE TITLE
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.

### ISSUE THREAD

**Issue by Gogan12** [ChiChou/bagbak#46]
**Describe the bug**
dump main app
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: 0x1011c96b5 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x10009cae9 node::Abort() [/usr/local/bin/node]
 3: 0x10009cc4f node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x1001e03a0 v8::V8::ToLocalEmpty() [/usr/local/bin/node]
 5: 0x105810e4e  [/usr/local/lib/node_modules/bagbak/node_modules/frida/build/Release/frida_binding.node]
 6: 0x10580cc6e  [/usr/local/lib/node_modules/bagbak/node_modules/frida/build/Release/frida_binding.node]
 7: 0x10580225b  [/usr/local/lib/node_modules/bagbak/node_modules/frida/build/Release/frida_binding.node]
 8: 0x10024a278 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
 9: 0x100249839 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
10: 0x100248f62 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
11: 0x1009d6159 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
12: 0x10095ba04 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
13: 0x10095ba04 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
zsh: abort      bagbak Chrome

**To Reproduce**
bagbag Chrome

**Expected behavior**
Im expected that app will be dumped )
**Desktop (please complete the following information):**
 - OS: MacOS 10.15.5
 - nodejs: v12.18.0
 - frida-node: 12.9.7
 - frida on device version 12.9.7
 - iOS and jailbreak version 13.4.1 Checkra1n JB v.0.10.2
 - The app you are trying to work on Chrome

**Comment by ChiChou** [comment]
duplicated #45

**Comment by Gogan12** [comment]
Im viewed issue #45, but you don't offered solution. Im tried to reinstall node, Frida and nothing changed. So, this is impossible to fix?

**Comment by ChiChou** [comment]
@oleavr it would be good if there is some instruciton on how to compile frida-node with symbols so I can dig into this

**Comment by Gogan12** [comment]
Im tried 1.6.0 - it works now, thanks!
