### ISSUE TITLE
Crashes process on large files

### ISSUE THREAD

**Issue by h0m3us3r** [ChiChou/bagbak#54]
**Describe the bug**
The being-dumped process crashes while it is being dumped if it has large resources.

**Log**
```
██████████████████░░░░░░░░░░░░░░░░░░░░░░ | 45% | 616.00Mib/1356.30MibFATAL ERROR
Error: Script is destroyed
```

**Desktop**
 - OS: MacOS Catalina
 - nodejs: v14.8.0
 - frida-node: v12.11.14
 - frida on device version: v12.11.14
 - iOS and jailbreak version: iPad Mini 4; 13.7; checkra1n
 - The app you are trying to work on: EVE Echoes

**Comment by andreaspijay** [comment]
I encounter the same issue. Instagram app. iOS 14.2, iPhone 7. Mac OS Big Sur.
