### ISSUE TITLE
Installation (npm install -g bagbak)

### ISSUE THREAD

**Issue by blakkbird9** [ChiChou/bagbak#55]
I can not install bagbak

Using:
         npm install -g bagbak

With the error:
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/artemio/.npm/_logs/2020-09-14T19_36_17_787Z-debug.log

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - nodejs: v12.18.3
 - frida-node: frida-12.11.14 
                     frida-tools-8.1.3
 - frida on device version: 12.11.14
 - iOS 13.5.1 and bootra1n 0.10.2

**Comment by ChiChou** [comment]
sudo
