### ISSUE TITLE
MacOS problem with new frida version

### ISSUE THREAD

**Issue by Gorge123** [ChiChou/bagbak#57]
**Describe the bug**
(frida:42673): Frida-CRITICAL **: 15:11:23.132: file ../../../frida-core/lib/interfaces/session.vala: line 167: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface ?re.frida.HostSession12? on object at path /re/frida/HostSession (g-dbus-error-quark, 19)

**To Reproduce**
bagbak -l

**Expected behavior**
List of apps installed

**Desktop (please complete the following information):**
 - OS: macOS
 - nodejs: v12.18.3
 - frida-node: 12.11.12 (newer cant be installed coz of prebuild-install WARN install No prebuilt binaries found (target=12.18.3 runtime=node arch=x64 libc= platform=darwin)
gyp: binding.gyp not found)
 
 - frida on device version 14.0.4
 - iOS and jailbreak version 13.5.1 jb checkra1n
 - The app you are trying to work on none

for now, its impossible to install bagbak without --force coz of "No prebuilt binaries found (target=12.18.3". Who can fix that issue?

**Comment by ChiChou** [comment]
Thanks for reporting! The latest frida-server has breaking changes, so I've upgraded the dependencies to fix them.

Please use bagbak@2.0.0

**Comment by ChiChou** [comment]
And ues node.js v14.x to fix "No prebuilt binaries found"

**Comment by Gorge123** [comment]
All is working now, thank you!
