### ISSUE TITLE
patch PluginKit validation FATAL ERROR

### ISSUE THREAD

**Issue by meefollow** [ChiChou/bagbak#59]
I have this error when it tries to decrypt the notification extension for the app

patch PluginKit validation
FATAL ERROR
Error [TypeError]: cannot read property 'implementation' of undefined
    at skipPkdValidationFor (agent/pkd.ts:11)
    at apply (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:13)
    at c (frida/runtime/message-dispatcher.js:23) {
  fileName: 'agent/pkd.ts',
  lineNumber: 11
}

iOS,14.2 
node v14.15.1
Running bagbak on Windows 10

**Comment by bamtan** [comment]
I am also getting the same error. 

```
patch PluginKit validation
FATAL ERROR
Error [TypeError]: cannot read property 'implementation' of undefined
    at skipPkdValidationFor (agent/pkd.ts:11)
    at apply (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:13)
    at c (frida/runtime/message-dispatcher.js:23) {
  fileName: 'agent/pkd.ts',
  lineNumber: 11
}
Exit status : 0
```

iOS 14.3
node v14.15.3
Frida pre-A12 v14.2.2
bagbak on macOS Big Sur

**Comment by GEEKiDoS** [comment]
Same
```
patch PluginKit validation
FATAL ERROR
Error [TypeError]: cannot read property 'implementation' of undefined
    at skipPkdValidationFor (agent/pkd.ts:11)
    at apply (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:13)
    at c (frida/runtime/message-dispatcher.js:23) {
  fileName: 'agent/pkd.ts',
  lineNumber: 11
}
```
iOS 14.3
node 14.15.3
Frida pre-A12 14.2.2
bagbak on Windows

**Comment by ChiChou** [comment]
Thanks for reporting.

iOS 14 introduced some change that caused this failure. I think I need to rewrite plenty of code

**Comment by ChiChou** [comment]
working now

**Comment by julepka** [comment]
I see a somewhat similar error on iOS 13.1.3. But still, I'm able to get the decrypted app and the error appears at the very end. Not sure if anything is actually broken.

Node version 14.17.0
bagbak version 2.0
Frida version 14.2.18
macOS BigSur

```
patch PluginKit validation
FATAL ERROR
[Error: Unable to attach to the specified process]
```
