### ISSUE TITLE
Bagbak not works with new frida 15

### ISSUE THREAD

**Issue by Gorge123** [ChiChou/bagbak#64]
**Describe the bug**
Nothing happened when you try to use bagbak

**To Reproduce**
just enter bagbak -l or bagbak com.package.name

**Desktop (please complete the following information):**
 - OS: macos
 - nodejs: 14.5.0
 - frida-node: 15.0.2
 - frida on device version 15.0.2
 - iOS and jailbreak version 14.5 checkra1n
 - The app you are trying to work on any

**Comment by a97077088** [comment]
https://github.com/a97077088/fd

The new tool runs, he doesn’t need any environment,

fd bagbak 通讯录

**Comment by Gorge123** [comment]
> https://github.com/a97077088/fd
> 
> The new tool runs, he doesn’t need any environment,
> 
> fd bagbak 通讯录

macos not supported

**Comment by a97077088** [comment]
@Gorge123 Now fd supports macos

https://github.com/a97077088/fd/releases/tag/15.0.12

**Comment by ChiChou** [comment]
I need a laptop to publish the newer version. Should be available next week

**Comment by ChiChou** [comment]
Sorry for the inconvenience

**Comment by ChiChou** [comment]
Latest patches published
