### ISSUE TITLE
m1 机器 bagbak --list 执行失败

### ISSUE THREAD

**Issue by WymanY** [ChiChou/bagbak#69]
**bagbak --list 失败**
直接直接bagbak --list失败

**如何复现**
安装完环境，直接执行bagbak --list

**Screenshots**
![image](https://user-images.githubusercontent.com/11940805/135254390-b6bfce16-fd53-493f-997e-2385dc013d81.png)

**Desktop (please complete the following information):**
 - OS:  m1 机器，MacOS  11.6
 - nodejs: v14.18.0
 - frida-node: frida-15.1.3
 - frida on device version : 15.1.3,
 - iOS and jailbreak version :  手机系统14.0.1，手机型号：iPhoneXS max

**Comment by ChiChou** [comment]
升级 node 至 v16 以上，重新 npm install -g bagbak

**Comment by WymanY** [comment]
> 升级 node 至 v16 以上，重新 npm install -g bagbak
可以了，升级到v16.10.0，执行没问题了，原因是m1的机器，node必须要升级到16版本吗？ 
node 16版本才兼容的m1??
另外是否可以修改下README,我当时就是按照README 来操作的。

**Comment by ChiChou** [comment]
frida 没给 arm 的 CPU 提供低版本的预编译

**Comment by WymanY** [comment]
感谢，大概知道什么原因了。辛苦大佬
