### ISSUE TITLE
Error: unable to unchain 8393

### ISSUE THREAD

**Issue by carppond** [ChiChou/bagbak#71]
download ...35411A8D6C/Aweme.app/PlugIns/AwemeVideoNotification.appex/AwemeVideoNotification
fetching decrypted data
████████████████████████████████████████ | 100% | 0.00Mib/0.00Mib
unable to dump plugins Error: unable to unchain 8393
Please file a bug to https://github.com/ChiChou/bagbak/issues
Error: unable to unchain 8393
    at dump (/usr/local/lib/node_modules/bagbak/go.js:314:17)
    at async main (/usr/local/lib/node_modules/bagbak/go.js:406:5)
Congrats!

**Comment by ChiChou** [comment]
Please use the issue template
