### ISSUE TITLE
Every dumped application doesn't have "embedded.mobileprovision" file.

### ISSUE THREAD

**Issue by vadimszzz** [ChiChou/bagbak#72]
<img width="691" alt="Screenshot 2022-01-10 at 4 09 47 PM" src="https://user-images.githubusercontent.com/92526019/148771270-e238b79b-6028-4d6a-9fa7-ae597aafc68d.png">
<img width="687" alt="Screenshot 2022-01-10 at 4 11 49 PM" src="https://user-images.githubusercontent.com/92526019/148771541-801f09b4-02c7-413f-9c00-75936e4ce599.png">

**Comment by xelzmm** [comment]
Entitlements can be found from within the binary file.

try 

```
ldid -S [binary]
```

**Comment by ChiChou** [comment]
Entitlements is part of the main executable. Please check @xelzmm 's reply

**Comment by vadimszzz** [comment]
> Entitlements is part of the main executable. Please check @xelzmm 's reply

Thanks. You can close the issue.

Can you advice please how to get entitlements using pure python? Any library like ldid in pure python or simple way to extract xml?

**Comment by ChiChou** [comment]
https://github.com/ChiChou/wiggle/blob/master/agent/codesign.py#L101

**Comment by vadimszzz** [comment]
> https://github.com/ChiChou/wiggle/blob/master/agent/codesign.py#L101

It’s a huge file with *lief* library used. 
I read Mach-O documentation and done this in 10 lines of pure python.
https://github.com/vadimszzz/codesign

Btw found one more Mach-O parser.
https://github.com/aaronst/macholibre

**Comment by ChiChou** [comment]
> > https://github.com/ChiChou/wiggle/blob/master/agent/codesign.py#L101
> 
> It’s a huge file with _lief_ library used. I read Mach-O documentation and done this in 10 lines of pure python. https://github.com/vadimszzz/codesign
> 
> Btw found one more Mach-O parser. https://github.com/aaronst/macholibre

You can pay for whatever you like
