### ISSUE TITLE
unable to dump plugins Error: unable to unchain 4573

### ISSUE THREAD

**Issue by YuXilong** [ChiChou/bagbak#77]
**Describe the bug**
bagbak xxx.app

unable to dump plugins Error: unable to unchain 4573
Please file a bug to https://github.com/ChiChou/bagbak/issues
Error: unable to unchain 4573
    at dump (/opt/homebrew/lib/node_modules/bagbak/go.js:314:17)
    at async main (/opt/homebrew/lib/node_modules/bagbak/go.js:406:5)
Congrats!

**To Reproduce**
Contains .appex applications

**Expected behavior**

**Screenshots**
<img width="599" alt="image" src="https://user-images.githubusercontent.com/13569008/173197125-222efc98-251d-42e8-bfc9-c961e40d5da4.png">

**Desktop (please complete the following information):**
 - OS: [M1 Max]
 - nodejs: [v18.2.0]
 - frida-node: [e.g. v15.1.22]
 - frida on device version
 - iOS and jailbreak version [14.3]
 - The app you are trying to work on [e.g. com.example.app]

**Additional context**

**Comment by ChiChou** [comment]
no way to reproduce
