### ISSUE TITLE
Cannot upload to TestFlight for Invalid Segment Alignment

### ISSUE THREAD

**Issue by rainbowcardiod** [ChiChou/bagbak#80]
I dumped an IPA with bagbak, and everything works fine, however, when I try to upload it to TestFlight with fastlane I get this error:

`ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'MyApp.app/PlugIns/MyPlugin.appex/MyPlugin' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."`

I also tried to give a segment alignment to binaries with `lipo $f -create -output $f`, which gives `align 2^14 (16384)`, but I still get the same error.

Is there a way to patch bagbak in order to make TestFlight happy? Do you have any suggestions?

**Comment by rainbowcardiod** [comment]
It turns out that the LC_ENCRYPTION_INFO_64 is not aligned. Running otool -l on the binary: 

```
Load command 14
          cmd LC_ENCRYPTION_INFO_64
          cmdsize 24
          cryptoff 20480
          cryptsize 4096
          cryptid 0
          pad 0
```

cryptoff and/or cryptsize is not a multiple of 16384, needed on arm64 iPhones.

Setting those value to zero resolves the problem.

**Comment by ChiChou** [comment]
Did you try to decrypt the app and then install on another phone?

**Comment by ChiChou** [comment]
The current version clears cryptoff and cryptsize completely
