### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by miticollo** [ChiChou/bagbak#83]
I used my **jailbroken** (Fugu14 + unc0ver) iPhone SE 2020 with iOS 14.4.2 to decrypt two apps: Telegram and Spotify. I wanted to install this two apps in my **unjailbroken** iPhone X (aka 10,6) with iOS 15.6 RC to test my frida scripts.

To do this:
1. I cloned your repo `git clone --recursive -j8 --depth 1 https://github.com/ChiChou/bagbak.git && cd bagbak`.
2. I plugged my iPhone SE 2020 with frida 16.0.2 to my Hackintosh (Intel i7).
3. I set node version using [`nvm`](https://github.com/nvm-sh/nvm): `nvm use 16` so `node v16.18.0 (npm v8.19.2)`.
4. Then I run `./go.js 'ph.telegra.Telegraph' && ./go.js 'com.spotify.client'`.
5. When command completed successfully I zipped **manually** (using Utily Compression inside macOS Monterey) `Payload` folders inside `dump/com.spotify.client/` and `dump/ph.telegra.Telegraph`.
6. I changed extension from `.zip` to `.ipa`. You can download IPAs from [here](https://drive.google.com/drive/folders/1Atd9CqQFv9T5-z8et_nao--cCvr3YAT9?usp=sharing).
7. To re-sign and install two IPAs I used [Sideloadly](https://sideloadly.io/).

Anyway when I open Spotify I have no problems while with Telegram don't crash but it shows a black screen. To understand better the situation you can watch a [video](https://drive.google.com/file/d/1iBnWAuelz0y0Il3mihyFDoyd_7D9-p7x/view?usp=sharing).

**Comment by ChiChou** [comment]
This tool is meant to dump the packages as-is. The blacksceen issue might be a trap from the app developer to prevent redistribution, by checking code signatures, bundle contents etc. You need to handle those things case by case
