### ISSUE TITLE
是否会适配ios15越狱新路径？

### ISSUE THREAD

**Issue by 961905** [ChiChou/bagbak#85]
/var/jb/usr/sbin/frida-server
/var/jb/usr/lib/frida/frida-agent.dylib/
var/jb/Library/LaunchDaemons/re.frida.server.plist

新越狱所安装的文件路径

**Comment by ChiChou** [comment]
设备端的 frida-server 配置不影响本项目运行

**Comment by ChiChou** [comment]
rootless 部署 frida-server
https://mp.weixin.qq.com/s/bq39dathhNUoZl5Uub6JAg
https://github.com/ChiChou/fruity-frida/
