### ISSUE TITLE
FATAL ERROR after patch PluginKit validation

### ISSUE THREAD

**Issue by jluo98** [ChiChou/bagbak#86]
**Describe the bug**
The decrypt process always fails with `FATAL ERROR` at `patch PluginKit validation`. Adding `--no-extension` would prevent the error (decrypted app would have no extensions of course). 
砸壳失败，总是在`patch PluginKit validation`的时候出现`FATAL ERROR`。用`--no-extension`可避免错误（当然，出来的app就没有extension了）。

**To Reproduce**
1. Clone and set up the repo
2. Run `./go.js com.tencent.xin`
3. Process stops after `patch PluginKit validation` prompting `FATAL ERROR` and `[Error: The connection is closed]`

**Expected behavior**
Successfully decrypt app with all extensions. 

**Screenshots**
[Logs](https://pastebin.com/mfa34Re6)

**Desktop (please complete the following information):**
 - OS: macOS 13.1
 - nodejs: v16.13.0
 - frida-node: v16.0.7
 - frida on device version: v16.0.7
 - iOS and jailbreak version: iOS 15.1 with [Palera1n](https://github.com/palera1n/palera1n) on iPhone 7 Plus
 - The app you are trying to work on: com.tencent.xin

**Additional context**
I manually adjusted `frida-node` to 16.0.7 but it did not help.

**Comment by ChiChou** [comment]
iOS 14 上一切正常，我没有对应的环境复现。需要 idevicecrashreport 里于 extension 相关的日志才能分析。猜想是因为 jetsam 补丁不起作用了

**Comment by jluo98** [comment]
我还不太了解iOS的report，不知道这份里面有没有有用的信息：[JetsamEvent-2022-12-12-132126.ips.txt](https://github.com/ChiChou/bagbak/files/10212292/JetsamEvent-2022-12-12-132126.ips.txt)

另外我用了[另一个project](https://github.com/AloneMonkey/frida-ios-dump)倒是成功拿到了带extension的ipa。

**Comment by itsmylife44** [comment]
use ` bagbak -zfn <bundleID>` 

working well on ios 15 and palnera1n

**Comment by ChiChou** [comment]
> use ` bagbak -zfn <bundleID>`
> 
> working well on ios 15 and palnera1n

yeah but he needs extensions

**Comment by ChiChou** [comment]
@jluo98 `idevicecrashreport` 命令可以复制所有的崩溃日志到电脑，而且默认会清空手机端的日志。可以先 idevicecrashreport，然后运行，第二次复制出来的日志就是新的

**Comment by jluo98** [comment]
> @jluo98 `idevicecrashreport` 命令可以复制所有的崩溃日志到电脑，而且默认会清空手机端的日志。可以先 idevicecrashreport，然后运行，第二次复制出来的日志就是新的

我上次的确是这么干的，但是崩溃之后没有新日志。我回头再试试看

**Comment by jluo98** [comment]
我又折腾了一下，成功 dump with extensions

设备：iPhone 7 Plus
iOS: 15.7.3
Jailbreak: Palera1n 2.0 Beta 4

我手动 checkout 了 169e6d5 commit （主要为了 frida 15）然后在手机上装上了 frida 15.0.13，成功 dump。可能还是 frida 16 有点问题。

**Comment by ChiChou** [comment]
I guess it's related to 8badf00d

**Comment by ChiChou** [comment]
https://github.com/frida/frida-core/issues/462
