### ISSUE TITLE
macos ventura bug?

### ISSUE THREAD

**Issue by Gorge123** [ChiChou/bagbak#87]
**Describe the bug**

bagbak net.openvpn.connect.app --override
app root: /var/containers/Bundle/Application/918E1062-9B01-4B9E-9D78-9456DB631E9
dump main app
download ...ners/Bundle/Application/918E1062-9B01-4B9E-9D78-9456DB631E9D/OpenVPN
████████████████████████████████████████ | 100% | 6.94Mib/6.94MibFATAL ERROR: se
reason: process-terminated
FATAL ERROR
Error: Script is destroyed
    at onScriptDestroyed (/usr/local/lib/node_modules/bagbak/node_modules/frida/

copied executable OpenVPN is still encrypted!

**To Reproduce**
just try to dump any app

**Desktop (please complete the following information):**
 - OS: macos 13.1
 - nodejs: v16.14.0
 - frida-node: 16.0.8
 - frida on device version 16.0.8
 - iOS and jailbreak version 14.5.1 checkra1n
 - The app you are trying to work on [e.g. com.example.app] any

**Comment by Nododo** [comment]
i have the same problem

**Comment by ChiChou** [comment]
same as https://github.com/ChiChou/bagbak/issues/88

**Comment by ChiChou** [comment]
2.5.0 removed `frida-fs` related code

**Comment by Nododo** [comment]
hi, can add update command to usage option?

thanks

**Comment by ChiChou** [comment]
> hi, can add update command to usage option?
> 
> thanks

https://docs.npmjs.com/updating-packages-downloaded-from-the-registry#updating-globally-installed-packages

**Comment by Nododo** [comment]
> > hi, can add update command to usage option?
> > thanks
> 
> https://docs.npmjs.com/updating-packages-downloaded-from-the-registry#updating-globally-installed-packages

thank you
