### ISSUE TITLE
Bagbak hangs after downloading the main executable

### ISSUE THREAD

**Issue by FieryFlames** [ChiChou/bagbak#88]
**Describe the bug**
Bagbak hangs after downloading the main executable

**To Reproduce**
Try running bagbak on Discord

**Expected behavior**
The app shouldn't hang and should continue on with whatever else it needs to do.

**Screenshots**
<img width="833" alt="Screenshot 2023-02-01 at 9 07 51 PM" src="https://user-images.githubusercontent.com/30497388/216213592-951002a7-f78b-4ad0-81b0-6aa5ee69f830.png">

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS (Debian 11 bullseye) arm64
 - nodejs: v18.13.0
 - frida-node: v8.19.3
 - frida on device: v16.0.8
 - iOS 12.5.7 with Odysseyra1n
 - com.hammerandchisel.discord

**Additional context**
Running on a iPod touch 6G, hoping to automate downloading latest Discord version using ipatool and decrypting using bagbak.
Host is a Raspberry Pi Zero 2 W

**Comment by Gorge123** [comment]
Check previos issue - Im have the same problem. Im though that its macos trouble. But now seems that the bug is in frida or just new frida is incompatible with bagbak (.

**Comment by FieryFlames** [comment]
I just got it working by downgrading Frida on the iPod to v15.2.2 and bagbak to v2.3.1. This should still be fixed ideally.

**Comment by ChiChou** [comment]
> I just got it working by downgrading Frida on the iPod to v15.2.2 and bagbak to v2.3.1. This should still be fixed ideally.

That's interesting..could be some frida issue

**Comment by jpstotz** [comment]
There seem to be multiple issues with bagbak, when using Frida 16.

The one that prevents the download to finish is https://github.com/frida/frida/issues/2447

**Comment by ChiChou** [comment]
> There seem to be multiple issues with bagbak, when using Frida 16.
> 
> The one that prevents the download to finish is [frida/frida#2447](https://github.com/frida/frida/issues/2447)

thanks a lot for digging the root cause!

**Comment by ChiChou** [comment]
fixed https://github.com/ChiChou/bagbak/commit/8035b981f0a40f727529bd8a4d933697328a63dd
