### ISSUE TITLE
Error: Unexpectedly timed out while waiting for app to launch

### ISSUE THREAD

**Issue by striveben** [ChiChou/bagbak#89]
**Describe the bug**
display 

FATAL ERROR
[Error: Unexpectedly timed out while waiting for app to launch]

![image](https://user-images.githubusercontent.com/61238912/219436130-669678a0-a090-4533-826f-90f4c36460a1.png)

![image](https://user-images.githubusercontent.com/61238912/219436373-05b87144-d28a-4a17-82ff-a86c3648d448.png)

**Desktop (please complete the following information):**
 - OS: [MacOs 13.2 (22D49)]
 - nodejs: [v14.19.0]
 - frida-node: [v15.1.11-node-v83]
 - frida on device version v15.1.11
 - iOS and jailbreak version   iOS 15.6
 - The app you are trying to work on [com.banma.smartTravel]

Thanks

**Comment by striveben** [comment]
And this wrong:
![image](https://user-images.githubusercontent.com/61238912/219437288-e4ccd1c8-d37e-4cd7-b5b6-219887968c93.png)

**Comment by ChiChou** [comment]
Please give v3.0.0 a try

https://github.com/ChiChou/bagbak/releases/tag/v3.0.0
