### ISSUE TITLE
Error: Script is destroyed

### ISSUE THREAD

**Issue by rxwy-y** [ChiChou/bagbak#92]
unable to dump plugins Error: Script is destroyed
Please file a bug to https://github.com/ChiChou/bagbak/issues
Error: Script is destroyed
    at onScriptDestroyed (/usr/local/lib/node_modules/bagbak/node_modules/frida/dist/script.js:125:26)
FATAL ERROR
[Error: Script is destroyed]

**Comment by ChiChou** [comment]
https://github.com/frida/frida-core/issues/462
