### ISSUE TITLE
Fails to install node 19.5.0 - frida 16.0.11

### ISSUE THREAD

**Issue by bensh** [ChiChou/bagbak#93]
**Describe the bug**
Doens't install on node 19.5.0 - npm 9.4.2

**To Reproduce**
npm install -g bagbak

**Expected behavior**
bagbak to be installed

Managed to install it on 14.17.0 but when trying to run getting, command not found.

**Desktop (please complete the following information):**
 - OS: macOS 12.6.3
 - nodejs: 19.5.0
 - frida-node: 16.0.11
 - frida on device version: 16.0.11
 - iOS and jailbreak version: 14.4 checkra1n

**Additional context**
`tools$ npm install -g bagbak    
npm ERR! code 1
npm ERR! path /Users/ben/.nvm/versions/node/v19.5.0/lib/node_modules/bagbak
npm ERR! command failed
npm ERR! command sh -c npm --prefix agent install
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /Users/ben/.nvm/versions/node/v19.5.0/lib/node_modules/bagbak
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c npm run build
npm ERR! npm ERR! > bagbak@2.5.1 build
npm ERR! npm ERR! > npm --prefix agent run build
npm ERR! npm ERR! 
npm ERR! npm ERR! 
npm ERR! npm ERR! > bagbak-agent@1.0.0 build
npm ERR! npm ERR! > npm run compile -- -c
npm ERR! npm ERR! 
npm ERR! npm ERR! 
npm ERR! npm ERR! > bagbak-agent@1.0.0 compile
npm ERR! npm ERR! > frida-compile src/index.ts -o dist/agent.js -c
npm ERR! npm ERR! 
npm ERR! npm ERR! unable to resolve: /Users/ben/.nvm/versions/node/v19.5.0/lib/node_modules/bagbak/agent/src/transfer, /Users/ben/.nvm/versions/node/v19.5.0/lib/node_modules/bagbak/agent/src/path, /Users/ben/.nvm/versions/node/v19.5.0/lib/node_modules/bagbak/agent/src/threads, /Users/ben/.nvm/versions/node/v19.5.0/lib/node_modules/bagbak/agent/src/dump, /Users/ben/.nvm/versions/node/v19.5.0/lib/node_modules/bagbak/agent/src/pkd, /Users/ben/.nvm/versions/node/v19.5.0/lib/node_modules/bagbak/agent/src/pluginkit
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/ben/.npm/_logs/2023-04-14T15_21_11_105Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ben/.npm/_logs/2023-04-14T15_21_05_001Z-debug-0.log`

**Comment by ChiChou** [comment]
Thanks for reporting!

**Comment by bensh** [comment]
Just tried it again, installs fine. Thanks for the fix
