### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mmas9689** [ChiChou/bagbak#94]
bagbak version 2.5.1 and 2.5.2 not working
please back to 2.5.0

C:\Users\Mahmood>bagbak -l
'bagbak' is not recognized as an internal or external command,
operable program or batch file.

**Comment by mtshare** [comment]
Same here on Mac Monterey after updating to the latest version

**Comment by ChiChou** [comment]
Sorry for the inconvenience

**Comment by ChiChou** [comment]
Wrote the patch like this

![image](https://user-images.githubusercontent.com/2802045/232238847-452bdf76-ba8f-4702-8e79-d2ccc8a4c8c0.jpeg)
