### ISSUE TITLE
Fatal Error, agent.js does not exist. Frida 16.0.14 nodeJS 19.5.0

### ISSUE THREAD

**Issue by gelosecurity** [ChiChou/bagbak#96]
**Describe the bug**
Fatal Error, agent.js does not exist.

**To Reproduce**
1. Install Frida 16.0.14 on iOS and MacOS.
2. Install bagbak using npm
3. bagbak -l is working
4. when attempting bagbak '[app]', get the following error:

```
FATAL ERROR
[Error: ENOENT: no such file or directory, open '/opt/homebrew/lib/node_modules/bagbak/agent/dist/agent.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/opt/homebrew/lib/node_modules/bagbak/agent/dist/agent.js'
}
```

**Expected behavior**
Should dump the app

**Desktop (please complete the following information):**
 - OS: MacOS
 - nodejs: v19.5.0
 - frida: 16.0.14
 - frida on device version: 16.0.14
 - iOS and jailbreak version: palera1n 15.7.3

**Comment by ChiChou** [comment]
There is a known issue(#93, #94) that v2.5.1 and v2.5.2 are incompletely published. Please make sure you are on the latest version: `npm install -g bagbak@2.5.3`

**Comment by bensh** [comment]
Still seems to have an issue

```
node_modules$ 
node_modules$ npm list -g         
/Users/ben/.nvm/versions/node/v19.5.0/lib
├── bagbak@2.5.3
└── frida@16.0.17

tools$ bagbak -u xxxxxxxxxxx com.app.internal -o /Users/ben/Documents/ios -z -f
FATAL ERROR
[Error: ENOENT: no such file or directory, open '/Users/ben/.nvm/versions/node/v19.5.0/lib/node_modules/bagbak/agent/dist/agent.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/ben/.nvm/versions/node/v19.5.0/lib/node_modules/bagbak/agent/dist/agent.js'
}
```

**Comment by ChiChou** [comment]
I deleted all 2.5.x releases. However the v2.5.3 failed to pull from npm because of too many downloads

**Comment by bensh** [comment]
Still getting this issue on 2.6.0

FATAL ERROR
[Error: ENOENT: no such file or directory, open '/Users/ben/.nvm/versions/node/v19.5.0/lib/node_modules/bagbak/agent/dist/agent.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/ben/.nvm/versions/node/v19.5.0/lib/node_modules/bagbak/agent/dist/agent.js'
}

npm list -g          
/Users/ben/.nvm/versions/node/v19.5.0/lib
├── bagbak@2.6.0
├── frida@16.0.17
├── grapefruit@0.2.0
└── retire@4.1.1

**Comment by ChiChou** [comment]
...pushed a new version again @bensh

**Comment by ChiChou** [comment]
@bensh npm is cursed. I tried https://github.com/ChiChou/bagbak/commit/0607d6b82f4572534fa8969a5448e1e0e63b6a54 bug it only works locally.

**Comment by ChiChou** [comment]
I am giving up on this, maybe I shoud ignore #90 and revert evrything to two weeks ago

**Comment by bensh** [comment]
Appreciate all the time you are putting into this for the community.

**Comment by ChiChou** [comment]
Should be working now
